dataiku:
  url: ${DATAIKU_ADAPTER_URL}/public/api

knime:
  url: ${KNIME_ADAPTER_URL}/rest/v4

trifacta:
  url: ${TRIFACTA_ADAPTER_URL}/v3

dsx:
  url: ${DSX_ADAPTER_URL}

nifi:
  url: ${NIFI_ADAPTER_URL}

glue:
  url: ${GLUE_ADAPTER_URL}

common:
  username: ${JOBMANAGER_USERNAME}
  password: ${JOBMANAGER_PASSWORD}
  tokenUrl: ${JOBMANAGER_TOKEN_URL}
  project: ${JOBMANAGER_PROJECT}
  job: ${JOBMANAGER_JOB}

spring:
  profiles:
    active: nifi,demo,none

server:
  port: 8081

