dataiku:
  url: http://${DATAIKU_ADAPTER_IP}:${DATAIKU_ADAPTER_PORT}/public/api
  apikey: ${DATAIKU_ADAPTER_KEY}

knime:
  url: ${KNIME_ADAPTER_URL}/rest/v4
  username: ${KNIME_ADAPTER_USERNAME}
  password: ${KNIME_ADAPTER_PASSWORD}

trifacta:
  url: ${TRIFACTA_ADAPTER_URL}/v3
  username: ${TRIFACTA_ADAPTER_USERNAME}
  password: ${TRIFACTA_ADAPTER_PASSWORD}

common:
  project: ${PREDEFINED_PROJECT}
  job: ${PREDEFINED_JOB}

spring:
  profiles:
    active: knime,demo

server:
  port: 8081

